# Generated by Django 4.2.4 on 2024-02-10 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diseases',
            fields=[
                ('DiseasesID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Deasesname', models.CharField(max_length=100)),
                ('DeasesDiscription', models.CharField(max_length=100)),
                ('commen_symptoms', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DrugName', models.CharField(max_length=50)),
                ('patientId', models.IntegerField()),
                ('prescriptionID', models.CharField(max_length=50)),
                ('exrays_test', models.ImageField(upload_to='photos%y%m%d')),
                ('diseasesId', models.IntegerField()),
                ('escortID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Escort',
            fields=[
                ('FirstName', models.CharField(max_length=100)),
                ('LasttName', models.CharField(max_length=100)),
                ('EscortID', models.IntegerField(primary_key=True, serialize=False)),
                ('Email', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('PhoneNumber', models.CharField(max_length=14)),
                ('yourHandel', models.CharField(max_length=100)),
                ('ProfilePicture', models.ImageField(upload_to='photos%y%m%d')),
                ('Male', models.BooleanField(default=True)),
                ('Female', models.BooleanField(default=False)),
                ('LastModified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['EscortID'],
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('Userhandel', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('DrugID', models.IntegerField(blank=True)),
                ('DrugName', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('purpose_of_use', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=100)),
                ('Duration_of_use', models.DateTimeField()),
                ('number_of_times_day', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('expire_date', models.DateField(blank=True)),
            ],
            options={
                'ordering': ['DrugName'],
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=100)),
                ('RePassword', models.CharField(max_length=100)),
                ('PhoneNumber', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('ReminderID', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('patientID', models.IntegerField(blank=True)),
                ('DrugName', models.CharField(blank=True, max_length=50)),
                ('StartDate', models.DateTimeField()),
                ('EndDate', models.DateTimeField()),
                ('State', models.BooleanField(blank=True)),
                ('AlarmRecordes', models.TimeField()),
                ('Audio', models.FileField(default='default_audio.mp3', upload_to='audio/')),
                ('Notes', models.TextField(max_length=50)),
            ],
            options={
                'ordering': ['ReminderID'],
            },
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('FirstName', models.CharField(max_length=100)),
                ('LasttName', models.CharField(max_length=100)),
                ('patientID', models.IntegerField(primary_key=True, serialize=False)),
                ('Email', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('PhoneNumber', models.CharField(max_length=100)),
                ('Handel', models.CharField(max_length=100)),
                ('ProfilePicture', models.ImageField(upload_to='photos%y%m%d')),
                ('Male', models.BooleanField(default=True)),
                ('Female', models.BooleanField(default=False)),
                ('DiseaseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erd.diseases')),
                ('deflut', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='erd.escort')),
            ],
            options={
                'ordering': ['patientID'],
            },
        ),
    ]
