# Generated by Django 4.2.4 on 2024-02-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erd', '0002_alter_diseases_options_alter_document_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escort',
            options={'ordering': ['yourHandel']},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['Handel']},
        ),
        migrations.AddField(
            model_name='register',
            name='emaill',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
