# Generated by Django 4.2.4 on 2024-02-10 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erd', '0003_alter_escort_options_alter_patient_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseases',
            name='DiseasesID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
